-- =============================================================================
-- Storks Rideshare Platform — Master Database Schema
-- =============================================================================
-- Convention:
--   • All PKs are UUID generated by the application (gen_random_uuid() fallback).
--   • Soft-deletes use (is_deleted BOOLEAN, deleted_at TIMESTAMPTZ).
--   • Audit cols: created_at (NOT NULL), updated_at.
--   • TIMESTAMPTZ is used throughout so all offsets are stored correctly.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- ENUM TYPES
-- ---------------------------------------------------------------------------

CREATE TYPE asset_type           AS ENUM ('IMAGE', 'DOCUMENT', 'VIDEO');
CREATE TYPE provider_type        AS ENUM ('GOOGLE', 'APPLE', 'EMAIL', 'CLERK');
CREATE TYPE role_type            AS ENUM ('PARENT', 'DRIVER', 'ADMIN');
CREATE TYPE payment_method       AS ENUM ('CARD', 'CASH', 'BANK_TRANSFER');
CREATE TYPE room_type            AS ENUM ('DIRECT', 'GROUP', 'OFFER');
CREATE TYPE message_type         AS ENUM ('CHAT', 'JOIN', 'LEAVE', 'TYPING', 'READ_RECEIPT', 'SYSTEM');
CREATE TYPE ride_status          AS ENUM (
    'RIDE_PENDING', 'RIDE_STARTED', 'RIDE_FINISHED',
    'RIDE_CANCELLED', 'RIDE_STALLED', 'RIDE_STOPPED'
);
CREATE TYPE leg_type             AS ENUM ('PICKUP', 'DROPOFF');
CREATE TYPE booking_type         AS ENUM ('MONTH', 'DAY');
CREATE TYPE offer_status         AS ENUM ('DRAFT', 'ACTIVE', 'PAUSED', 'CLOSED');
CREATE TYPE verification_type    AS ENUM ('morning_otp', 'afternoon_otp', 'morning_qr', 'afternoon_qr');
CREATE TYPE verification_status  AS ENUM ('success', 'failure', 'expired');

-- ---------------------------------------------------------------------------
-- CORE USER TABLES
-- ---------------------------------------------------------------------------

CREATE TABLE users
(
    user_id             UUID         NOT NULL,
    -- Joined-inheritance discriminator column
    user_type           VARCHAR(31)  NOT NULL,
    email               VARCHAR(255),
    first_name          VARCHAR(255),
    last_name           VARCHAR(255),
    provider_type       provider_type NOT NULL,
    provider_user_id    VARCHAR(255) NOT NULL,
    role                role_type,
    profile_picture_url VARCHAR(255),
    onboarded           BOOLEAN      NOT NULL DEFAULT FALSE,
    banned              BOOLEAN      NOT NULL DEFAULT FALSE,
    -- Audit / tracking
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    last_logged_in      TIMESTAMPTZ,
    -- Soft delete
    is_deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_provider UNIQUE (provider_type, provider_user_id)
);

CREATE TABLE parents
(
    user_id            UUID         NOT NULL,
    payment_preferred  payment_method,
    -- Embedded primary phone (PhoneNumber @Embeddable)
    country_code       VARCHAR(10)  NOT NULL,
    number             VARCHAR(20)  NOT NULL,
    "primary"          BOOLEAN      NOT NULL DEFAULT TRUE,
    is_validated       BOOLEAN      NOT NULL DEFAULT FALSE,
    -- Audit
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ,
    CONSTRAINT pk_parents PRIMARY KEY (user_id)
);

CREATE TABLE parent_secondary_phones
(
    parent_id    UUID        NOT NULL,
    country_code VARCHAR(10) NOT NULL,
    number       VARCHAR(20) NOT NULL,
    "primary"    BOOLEAN     DEFAULT FALSE,
    is_validated BOOLEAN     DEFAULT FALSE,
    added_at     TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ
);

CREATE TABLE drivers
(
    user_id      UUID        NOT NULL,
    -- Embedded primary phone
    country_code VARCHAR(10) NOT NULL,
    number       VARCHAR(20) NOT NULL,
    "primary"    BOOLEAN     NOT NULL DEFAULT TRUE,
    is_validated BOOLEAN     NOT NULL DEFAULT FALSE,
    -- Audit
    added_at     TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ,
    CONSTRAINT pk_drivers PRIMARY KEY (user_id)
);

CREATE TABLE driver_secondary_phones
(
    driver_id    UUID        NOT NULL,
    country_code VARCHAR(10) NOT NULL,
    number       VARCHAR(20) NOT NULL,
    "primary"    BOOLEAN     DEFAULT FALSE,
    is_validated BOOLEAN     DEFAULT FALSE,
    added_at     TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ
);

CREATE TABLE driver_licences
(
    license_id     UUID         NOT NULL,
    license_number VARCHAR(100),
    driver_id      UUID,
    -- Audit
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ,
    -- Verification
    verified_at    TIMESTAMPTZ,
    is_verified    BOOLEAN      NOT NULL DEFAULT FALSE,
    expiry_date    DATE,
    CONSTRAINT pk_driver_licences PRIMARY KEY (license_id)
);

-- ---------------------------------------------------------------------------
-- CHILDREN & GROUPS
-- ---------------------------------------------------------------------------

CREATE TABLE child_groups
(
    group_id                    UUID NOT NULL,
    parent_id                   UUID,
    pickup_location_id          UUID,
    default_dropoff_location_id UUID,
    -- Ride currently assigned to this group
    ride_id                     UUID,
    -- Audit
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ,
    -- Soft delete
    is_deleted                  BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at                  TIMESTAMPTZ,
    CONSTRAINT pk_child_groups PRIMARY KEY (group_id)
);

CREATE TABLE children
(
    child_id       UUID         NOT NULL,
    parent_id      UUID,
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    preferred_name VARCHAR(255),
    pronouns       VARCHAR(50),
    grade          VARCHAR(50),
    group_id       UUID,
    qr_hash        VARCHAR(255),
    -- Embedded School (@Embeddable - reserved for future columns)
    school_name    VARCHAR(255),
    school_address VARCHAR(512),
    -- Audit
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ,
    -- Soft delete
    is_deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at     TIMESTAMPTZ,
    CONSTRAINT pk_children PRIMARY KEY (child_id)
);

-- ---------------------------------------------------------------------------
-- LOCATIONS
-- ---------------------------------------------------------------------------

CREATE TABLE locations
(
    location_id UUID    NOT NULL,
    address     VARCHAR(512),
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    latitude    DECIMAL(10, 7) NOT NULL,
    longitude   DECIMAL(10, 7) NOT NULL,
    nickname    VARCHAR(255),
    -- Optional owner (user who created/owns this saved location)
    owner_id    UUID,
    -- Audit
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    -- Soft delete
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,
    CONSTRAINT pk_locations PRIMARY KEY (location_id)
);

-- ---------------------------------------------------------------------------
-- ASSETS & VEHICLES
-- ---------------------------------------------------------------------------

CREATE TABLE assets
(
    asset_id    UUID NOT NULL,
    type        asset_type,
    asset_url   VARCHAR(512),
    -- Who uploaded (optional)
    uploaded_by UUID,
    -- Audit
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    -- Soft delete
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,
    CONSTRAINT pk_assets PRIMARY KEY (asset_id)
);

CREATE TABLE vehicles
(
    vehicle_id    UUID         NOT NULL,
    nickname      VARCHAR(255),
    license_plate VARCHAR(50)  NOT NULL,
    driver_id     UUID,
    -- Vehicle metadata
    make          VARCHAR(100),
    model         VARCHAR(100),
    year          SMALLINT,
    color         VARCHAR(50),
    -- Audit
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ,
    -- Soft delete
    is_deleted    BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMPTZ,
    CONSTRAINT pk_vehicles PRIMARY KEY (vehicle_id)
);

CREATE TABLE vehicle_assets
(
    asset_id   UUID NOT NULL,
    vehicle_id UUID NOT NULL
);

-- ---------------------------------------------------------------------------
-- OFFERS
-- ---------------------------------------------------------------------------

CREATE TABLE offers
(
    offer_id                     UUID             NOT NULL,
    driver_id                    UUID,
    vehicle_id                   UUID,
    is_using_intelligent_pricing BOOLEAN          NOT NULL DEFAULT FALSE,
    price_per_month              DOUBLE PRECISION NOT NULL DEFAULT 0,
    price_per_day                DOUBLE PRECISION NOT NULL DEFAULT 0,
    status                       offer_status     NOT NULL DEFAULT 'DRAFT',
    description                  TEXT,
    -- Maximum children capacity
    max_children                 SMALLINT,
    -- Analytics
    total_bookings               INTEGER          NOT NULL DEFAULT 0,
    -- Audit
    created_at                   TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    updated_at                   TIMESTAMPTZ,
    -- Soft delete
    is_deleted                   BOOLEAN          NOT NULL DEFAULT FALSE,
    deleted_at                   TIMESTAMPTZ,
    CONSTRAINT pk_offers PRIMARY KEY (offer_id)
);

CREATE TABLE offer_destinations
(
    location_id UUID NOT NULL,
    offer_id    UUID NOT NULL
);

-- ---------------------------------------------------------------------------
-- BOOKINGS
-- ---------------------------------------------------------------------------

CREATE TABLE bookings
(
    id           UUID         NOT NULL,
    parent_id    UUID,
    offer_id     UUID,
    group_id     UUID,
    start_date   DATE,
    end_date     DATE,
    type         booking_type,
    -- State
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    is_cancelled BOOLEAN      NOT NULL DEFAULT FALSE,
    cancelled_at TIMESTAMPTZ,
    cancel_reason VARCHAR(512),
    -- Analytics
    total_paid   DOUBLE PRECISION     DEFAULT 0,
    -- Audit
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------------
-- RIDES & LEGS
-- ---------------------------------------------------------------------------

CREATE TABLE rides
(
    ride_id      UUID         NOT NULL,
    driver_id    UUID,
    offer_id     UUID,
    status       ride_status  NOT NULL DEFAULT 'RIDE_PENDING',
    -- Scheduling
    scheduled_at TIMESTAMPTZ,
    -- Lifecycle timestamps
    started_at   TIMESTAMPTZ,
    ended_at     TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    -- Analytics
    total_distance_km DECIMAL(10, 3),
    total_duration_min INTEGER,
    -- Audit
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ,
    CONSTRAINT pk_rides PRIMARY KEY (ride_id)
);

CREATE TABLE ride_legs
(
    id         UUID     NOT NULL,
    ride_id    UUID,
    type       leg_type,
    start_time TIMESTAMPTZ,
    end_time   TIMESTAMPTZ,
    -- Optional location snapshots at start/end of leg
    start_latitude  DECIMAL(10, 7),
    start_longitude DECIMAL(10, 7),
    end_latitude    DECIMAL(10, 7),
    end_longitude   DECIMAL(10, 7),
    -- Audit
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_ride_legs PRIMARY KEY (id)
);

-- Tracks per-child attendance/presence on a given ride day
-- (referenced in safety-and-verification as "ride_passangers" — corrected spelling)
CREATE TABLE ride_passengers
(
    id                    UUID    NOT NULL,
    ride_id               UUID    NOT NULL,
    child_id              UUID    NOT NULL,
    date                  DATE    NOT NULL,
    morning_attendance    BOOLEAN NOT NULL DEFAULT FALSE,
    afternoon_attendance  BOOLEAN NOT NULL DEFAULT FALSE,
    -- Audit
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ,
    CONSTRAINT pk_ride_passengers PRIMARY KEY (id),
    CONSTRAINT uq_ride_passengers UNIQUE (ride_id, child_id, date)
);

-- ---------------------------------------------------------------------------
-- SCHEDULES
-- ---------------------------------------------------------------------------

CREATE TABLE schedules
(
    schedule_id         UUID NOT NULL,
    date                DATE,
    dropoff_location_id UUID,
    pickup_location_id  UUID,
    child_id            UUID,
    -- Override group defaults for this day
    is_custom           BOOLEAN     NOT NULL DEFAULT FALSE,
    -- Cancellation
    is_cancelled        BOOLEAN     NOT NULL DEFAULT FALSE,
    cancelled_at        TIMESTAMPTZ,
    -- Audit
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    CONSTRAINT pk_schedules PRIMARY KEY (schedule_id)
);

-- ---------------------------------------------------------------------------
-- PAYMENTS / CARDS
-- ---------------------------------------------------------------------------

CREATE TABLE cards
(
    card_id          UUID         NOT NULL,
    card_number      VARCHAR(255) NOT NULL,
    card_holder_name VARCHAR(255) NOT NULL,
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    is_primary       BOOLEAN      NOT NULL DEFAULT FALSE,
    parent_id        UUID,
    -- Card metadata
    expires_at       DATE,
    last_four        VARCHAR(4),
    card_brand       VARCHAR(50),
    -- Audit
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ,
    -- Soft delete
    is_deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMPTZ,
    CONSTRAINT pk_cards PRIMARY KEY (card_id)
);

-- ---------------------------------------------------------------------------
-- MESSAGING
-- ---------------------------------------------------------------------------

CREATE TABLE chat_rooms
(
    room_id        UUID         NOT NULL,
    chat_room_type room_type,
    offer_id       UUID,
    -- Audit
    created_at     TIMESTAMPTZ,
    updated_at     TIMESTAMPTZ,
    -- Soft delete
    is_deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at     TIMESTAMPTZ,
    CONSTRAINT pk_chat_rooms PRIMARY KEY (room_id)
);

CREATE TABLE chat_room_participants
(
    id         UUID    NOT NULL,
    room_id    UUID    NOT NULL,
    user_id    UUID    NOT NULL,
    joined_at  TIMESTAMPTZ DEFAULT NOW(),
    left_at    TIMESTAMPTZ,
    is_removed BOOLEAN DEFAULT FALSE,
    CONSTRAINT pk_chat_room_participants PRIMARY KEY (id)
);

CREATE TABLE messages
(
    message_id UUID         NOT NULL,
    room_id    UUID,
    sent_at    TIMESTAMPTZ,
    sender_id  UUID,
    content    TEXT,
    type       message_type NOT NULL DEFAULT 'CHAT',
    -- Soft delete
    is_deleted BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    -- Edit tracking
    is_edited  BOOLEAN      NOT NULL DEFAULT FALSE,
    edited_at  TIMESTAMPTZ,
    CONSTRAINT pk_messages PRIMARY KEY (message_id)
);

CREATE TABLE message_read_by
(
    message_id UUID NOT NULL,
    user_id    UUID NOT NULL,
    read_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- SAFETY & VERIFICATION
-- ---------------------------------------------------------------------------

-- Pre-generated afternoon OTPs for child pickup (one per child per date)
CREATE TABLE afternoon_otps
(
    id          UUID NOT NULL,
    group_id    UUID NOT NULL,
    child_id    UUID NOT NULL,
    pin         VARCHAR(10) NOT NULL,
    active_date DATE        NOT NULL,
    -- Audit
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Optional: mark as used
    used        BOOLEAN     NOT NULL DEFAULT FALSE,
    used_at     TIMESTAMPTZ,
    CONSTRAINT pk_afternoon_otps PRIMARY KEY (id),
    CONSTRAINT uq_afternoon_otps UNIQUE (group_id, child_id, active_date)
);

-- Immutable audit trail for every QR/OTP verification attempt
CREATE TABLE verification_logs
(
    id                UUID                NOT NULL,
    verification_type verification_type   NOT NULL,
    status            verification_status NOT NULL DEFAULT 'success',
    ride_id           UUID,
    group_id          UUID,
    child_id          UUID,
    driver_id         UUID,
    -- Extra context (e.g. failure reason)
    failure_reason    VARCHAR(512),
    -- IP / device info for fraud analytics
    ip_address        INET,
    device_info       JSONB,
    verified_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_verification_logs PRIMARY KEY (id)
);

-- =============================================================================
-- UNIQUE CONSTRAINTS
-- =============================================================================

ALTER TABLE vehicle_assets
    ADD CONSTRAINT uq_vehicle_assets_asset UNIQUE (asset_id);

ALTER TABLE schedules
    ADD CONSTRAINT uq_schedules_child_date UNIQUE (child_id, date);

ALTER TABLE cards
    ADD CONSTRAINT uq_cards_card_number UNIQUE (card_number);

ALTER TABLE driver_licences
    ADD CONSTRAINT uq_driver_licences_driver UNIQUE (driver_id);

ALTER TABLE offer_destinations
    ADD CONSTRAINT uq_offer_destinations_location UNIQUE (location_id);

ALTER TABLE offers
    ADD CONSTRAINT uq_offers_driver UNIQUE (driver_id);

ALTER TABLE offers
    ADD CONSTRAINT uq_offers_vehicle UNIQUE (vehicle_id);

ALTER TABLE vehicles
    ADD CONSTRAINT uq_vehicles_driver UNIQUE (driver_id);

ALTER TABLE vehicles
    ADD CONSTRAINT uq_vehicles_license_plate UNIQUE (license_plate);

-- =============================================================================
-- FOREIGN KEY CONSTRAINTS
-- =============================================================================

-- users
ALTER TABLE parents
    ADD CONSTRAINT fk_parents_on_user FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE drivers
    ADD CONSTRAINT fk_drivers_on_user FOREIGN KEY (user_id) REFERENCES users (user_id);

-- phones
ALTER TABLE parent_secondary_phones
    ADD CONSTRAINT fk_parent_secondary_phones_on_parent FOREIGN KEY (parent_id) REFERENCES parents (user_id);

ALTER TABLE driver_secondary_phones
    ADD CONSTRAINT fk_driver_secondary_phones_on_driver FOREIGN KEY (driver_id) REFERENCES drivers (user_id);

-- licences
ALTER TABLE driver_licences
    ADD CONSTRAINT fk_driver_licences_on_driver FOREIGN KEY (driver_id) REFERENCES drivers (user_id);

-- children & groups
ALTER TABLE child_groups
    ADD CONSTRAINT fk_child_groups_on_parent FOREIGN KEY (parent_id) REFERENCES parents (user_id);

ALTER TABLE child_groups
    ADD CONSTRAINT fk_child_groups_on_pickup_location FOREIGN KEY (pickup_location_id) REFERENCES locations (location_id);

ALTER TABLE child_groups
    ADD CONSTRAINT fk_child_groups_on_default_dropoff_location FOREIGN KEY (default_dropoff_location_id) REFERENCES locations (location_id);

ALTER TABLE child_groups
    ADD CONSTRAINT fk_child_groups_on_ride FOREIGN KEY (ride_id) REFERENCES rides (ride_id);

ALTER TABLE children
    ADD CONSTRAINT fk_children_on_parent FOREIGN KEY (parent_id) REFERENCES parents (user_id);

ALTER TABLE children
    ADD CONSTRAINT fk_children_on_group FOREIGN KEY (group_id) REFERENCES child_groups (group_id);

-- locations
ALTER TABLE locations
    ADD CONSTRAINT fk_locations_on_owner FOREIGN KEY (owner_id) REFERENCES users (user_id);

-- assets
ALTER TABLE assets
    ADD CONSTRAINT fk_assets_on_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users (user_id);

-- vehicles
ALTER TABLE vehicles
    ADD CONSTRAINT fk_vehicles_on_driver FOREIGN KEY (driver_id) REFERENCES drivers (user_id);

ALTER TABLE vehicle_assets
    ADD CONSTRAINT fk_vehicle_assets_on_asset FOREIGN KEY (asset_id) REFERENCES assets (asset_id);

ALTER TABLE vehicle_assets
    ADD CONSTRAINT fk_vehicle_assets_on_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id);

-- offers
ALTER TABLE offers
    ADD CONSTRAINT fk_offers_on_driver FOREIGN KEY (driver_id) REFERENCES drivers (user_id);

ALTER TABLE offers
    ADD CONSTRAINT fk_offers_on_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id);

ALTER TABLE offer_destinations
    ADD CONSTRAINT fk_offer_destinations_on_location FOREIGN KEY (location_id) REFERENCES locations (location_id);

ALTER TABLE offer_destinations
    ADD CONSTRAINT fk_offer_destinations_on_offer FOREIGN KEY (offer_id) REFERENCES offers (offer_id);

-- bookings
ALTER TABLE bookings
    ADD CONSTRAINT fk_bookings_on_parent FOREIGN KEY (parent_id) REFERENCES parents (user_id);

ALTER TABLE bookings
    ADD CONSTRAINT fk_bookings_on_offer FOREIGN KEY (offer_id) REFERENCES offers (offer_id);

ALTER TABLE bookings
    ADD CONSTRAINT fk_bookings_on_group FOREIGN KEY (group_id) REFERENCES child_groups (group_id);

-- rides
ALTER TABLE rides
    ADD CONSTRAINT fk_rides_on_driver FOREIGN KEY (driver_id) REFERENCES drivers (user_id);

ALTER TABLE rides
    ADD CONSTRAINT fk_rides_on_offer FOREIGN KEY (offer_id) REFERENCES offers (offer_id);

ALTER TABLE ride_legs
    ADD CONSTRAINT fk_ride_legs_on_ride FOREIGN KEY (ride_id) REFERENCES rides (ride_id);

ALTER TABLE ride_passengers
    ADD CONSTRAINT fk_ride_passengers_on_ride FOREIGN KEY (ride_id) REFERENCES rides (ride_id);

ALTER TABLE ride_passengers
    ADD CONSTRAINT fk_ride_passengers_on_child FOREIGN KEY (child_id) REFERENCES children (child_id);

-- schedules
ALTER TABLE schedules
    ADD CONSTRAINT fk_schedules_on_child FOREIGN KEY (child_id) REFERENCES children (child_id);

ALTER TABLE schedules
    ADD CONSTRAINT fk_schedules_on_pickup_location FOREIGN KEY (pickup_location_id) REFERENCES locations (location_id);

ALTER TABLE schedules
    ADD CONSTRAINT fk_schedules_on_dropoff_location FOREIGN KEY (dropoff_location_id) REFERENCES locations (location_id);

-- cards
ALTER TABLE cards
    ADD CONSTRAINT fk_cards_on_parent FOREIGN KEY (parent_id) REFERENCES parents (user_id);

-- chat
ALTER TABLE chat_rooms
    ADD CONSTRAINT fk_chat_rooms_on_offer FOREIGN KEY (offer_id) REFERENCES offers (offer_id);

ALTER TABLE chat_room_participants
    ADD CONSTRAINT fk_chat_room_participants_on_room FOREIGN KEY (room_id) REFERENCES chat_rooms (room_id);

ALTER TABLE chat_room_participants
    ADD CONSTRAINT fk_chat_room_participants_on_user FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE messages
    ADD CONSTRAINT fk_messages_on_room FOREIGN KEY (room_id) REFERENCES chat_rooms (room_id);

ALTER TABLE messages
    ADD CONSTRAINT fk_messages_on_sender FOREIGN KEY (sender_id) REFERENCES users (user_id);

ALTER TABLE message_read_by
    ADD CONSTRAINT fk_message_read_by_on_message FOREIGN KEY (message_id) REFERENCES messages (message_id);

ALTER TABLE message_read_by
    ADD CONSTRAINT fk_message_read_by_on_user FOREIGN KEY (user_id) REFERENCES users (user_id);

-- safety & verification
ALTER TABLE afternoon_otps
    ADD CONSTRAINT fk_afternoon_otps_on_group FOREIGN KEY (group_id) REFERENCES child_groups (group_id);

ALTER TABLE afternoon_otps
    ADD CONSTRAINT fk_afternoon_otps_on_child FOREIGN KEY (child_id) REFERENCES children (child_id);

ALTER TABLE verification_logs
    ADD CONSTRAINT fk_verification_logs_on_ride FOREIGN KEY (ride_id) REFERENCES rides (ride_id);

ALTER TABLE verification_logs
    ADD CONSTRAINT fk_verification_logs_on_group FOREIGN KEY (group_id) REFERENCES child_groups (group_id);

ALTER TABLE verification_logs
    ADD CONSTRAINT fk_verification_logs_on_child FOREIGN KEY (child_id) REFERENCES children (child_id);

ALTER TABLE verification_logs
    ADD CONSTRAINT fk_verification_logs_on_driver FOREIGN KEY (driver_id) REFERENCES drivers (user_id);

-- =============================================================================
-- PERFORMANCE INDEXES
-- =============================================================================

-- User lookups
CREATE INDEX idx_users_email            ON users (email);
CREATE INDEX idx_users_provider         ON users (provider_type, provider_user_id);
CREATE INDEX idx_users_is_deleted       ON users (is_deleted);

-- Children
CREATE INDEX idx_children_parent        ON children (parent_id);
CREATE INDEX idx_children_group         ON children (group_id);

-- Rides
CREATE INDEX idx_rides_driver           ON rides (driver_id);
CREATE INDEX idx_rides_status           ON rides (status);
CREATE INDEX idx_rides_offer            ON rides (offer_id);

-- Ride passengers (most-queried in safety service)
CREATE INDEX idx_ride_passengers_ride_date ON ride_passengers (ride_id, date);

-- Schedules
CREATE INDEX idx_schedules_child_date   ON schedules (child_id, date);

-- Messages (time-ordered per room)
CREATE INDEX idx_messages_room_sent     ON messages (room_id, sent_at DESC);

-- Verification logs (analytics queries)
CREATE INDEX idx_verification_logs_type_at  ON verification_logs (verification_type, verified_at);
CREATE INDEX idx_verification_logs_ride     ON verification_logs (ride_id);

-- Afternoon OTPs (looked up by group + child + date)
CREATE INDEX idx_afternoon_otps_lookup  ON afternoon_otps (group_id, child_id, active_date);

-- Offers
CREATE INDEX idx_offers_status          ON offers (status);

-- Bookings
CREATE INDEX idx_bookings_parent        ON bookings (parent_id);
CREATE INDEX idx_bookings_offer         ON bookings (offer_id);
CREATE INDEX idx_bookings_dates         ON bookings (start_date, end_date);