version: '3.8'

services:
  safty-service:
    build: .
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
    env_file:
      - security.env
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
