import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1a0f0a",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 16,
    alignItems: "center",
  },
  logo: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
  },
  profile: {
    padding: 4,
  },
  scrollView: {
    flex: 1,
  },
  banner: {
    height: 150,
    backgroundColor: "#332211",
    borderRadius: 12,
    margin: 16,
    padding: 16,
    justifyContent: "space-between",
    overflow: "hidden",
  },
  coverImage: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
    opacity: 0.6,
  },
  backButton: {
    padding: 4,
  },
  editGroupBtn: {
    alignSelf: "flex-end",
    backgroundColor: "#ff6a00",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  editGroupText: {
    color: "white",
    fontSize: 12,
    fontWeight: "600",
  },
  groupName: {
    color: "#ff6a00",
    fontSize: 28,
    fontWeight: "bold",
    marginHorizontal: 16,
    marginBottom: 8,
  },
  sectionTitle: {
    color: "white",
    fontSize: 18,
    fontWeight: "600",
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 10,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2a1a14",
    marginHorizontal: 16,
    marginBottom: 8,
    padding: 12,
    borderRadius: 12,
  },
  avatarPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#443322",
    marginRight: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  infoContainer: {
    flex: 1,
  },
  primaryText: {
    color: "white",
    fontSize: 16,
    fontWeight: "500",
  },
  secondaryText: {
    color: "#aaa",
    fontSize: 13,
    marginTop: 2,
  },
  actionIcon: {
    padding: 4,
  },
  dashedBox: {
    marginHorizontal: 16,
    marginTop: 8,
    padding: 20,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#443322",
    borderStyle: "dashed",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 106, 0, 0.05)",
  },
  dashedBoxText: {
    color: "#ccc",
    fontSize: 14,
    flex: 1,
    lineHeight: 20,
  },
  dashedBoxIcon: {
    marginLeft: 12,
  },
  driverCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2a1a14",
    marginHorizontal: 16,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#3a2a24",
  },
  badge: {
    borderWidth: 1,
    borderColor: "#ff6a00",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    marginTop: 6,
    alignSelf: "flex-start",
  },
  badgeText: {
    color: "#ff6a00",
    fontSize: 10,
    fontWeight: "bold",
  },
  vehicleInfo: {
    alignItems: "flex-end",
  },
  vehiclePlate: {
    color: "#ff6a00",
    fontSize: 14,
    fontWeight: "bold",
  },
  paymentStatus: {
    marginTop: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: "rgba(0, 255, 0, 0.1)",
    borderWidth: 1,
    borderColor: "lime",
  },
  paymentText: {
    color: "lime",
    fontSize: 10,
    fontWeight: "bold",
  },
  buttonContainer: {
    flexDirection: "row",
    padding: 16,
    marginTop: 10,
    marginBottom: 20,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: "#ff6a00",
    height: 54,
    borderRadius: 27,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#ff6a00",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  primaryButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: "#33221a",
    height: 54,
    borderRadius: 27,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 12,
  },
  secondaryButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
  },
  navbar: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingVertical: 12,
    backgroundColor: "#1a0f0a",
    borderTopWidth: 1,
    borderTopColor: "#2a1a14",
  },
  navItem: {
    padding: 8,
  },
  errorText: {
    color: "#ff4444",
    fontSize: 14,
    textAlign: "center",
    margin: 20,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#1a0f0a",
  },
});
