spring.application.name=live-messaging
# spring.datasource.url=jdbc:postgresql://ep-damp-poetry-a17mj41n-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require

## DATABASE
spring.datasource.url=jdbc:postgresql://ep-holy-credit-a118kh6w-pooler.ap-southeast-1.aws.neon.tech/storks?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_CPy4FrjaeO9l
spring.jpa.hibernate.ddl-auto=validate

## REDIS
spring.data.redis.url=redis://default:tLqqIFHmEGaax3G7him6YkyqFkulPoWG@redis-13088.crce276.ap-south-1-3.ec2.cloud.redislabs.com:13088
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

## KAFKA
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=live-messaging-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

## DEVTOOLS
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://real-bird-20.clerk.accounts.dev
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://real-bird-20.clerk.accounts.dev/.well-known/jwks.json