spring:
  application:
    name: live-messaging
  datasource:
    url: ${NEON_DB_URL}
    username: ${NEON_DB_USERNAME}
    password: ${NEON_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://real-bird-20.clerk.accounts.dev
          jwk-set-uri: https://real-bird-20.clerk.accounts.dev/.well-known/jwks.json

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

storks:
  internal:
    user-service-url: ${USER_SERVICE_URL:http://user-service:8083}
    api-key: ${INTERNAL_API_KEY}