onlyBuiltDependencies:
  - ','
  - '-'
  - /
  - '8'
  - '@'
  - '@clerk/shared'
  - a
  - b
  - browser-tabs-lock
  - bufferutil
  - c
  - core-js
  - d
  - e
  - f
  - h
  - i
  - j
  - k
  - l
  - o
  - r
  - s
  - t
  - u
  - utf-8-validate
  - v
  - w
